// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD82fm2AYQ7dD9MY5SJHIsJtxPPH9ftO60',
    appId: '1:565159665428:web:d8c10e2f3d361f8ae8ac01',
    messagingSenderId: '565159665428',
    projectId: 'laundry-c3745',
    authDomain: 'laundry-c3745.firebaseapp.com',
    storageBucket: 'laundry-c3745.appspot.com',
    measurementId: 'G-ZYE6GSJH4D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANVCE8EalnchlhG_v8zr773_Del1nhJWU',
    appId: '1:565159665428:android:ea0bbd5909afb5d1e8ac01',
    messagingSenderId: '565159665428',
    projectId: 'laundry-c3745',
    storageBucket: 'laundry-c3745.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXHIBfr8Z1WpOpptB5n0c_7bPxBLvFyIw',
    appId: '1:565159665428:ios:5a8b5e3aa4f3da31e8ac01',
    messagingSenderId: '565159665428',
    projectId: 'laundry-c3745',
    storageBucket: 'laundry-c3745.appspot.com',
    iosBundleId: 'com.example.uas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXHIBfr8Z1WpOpptB5n0c_7bPxBLvFyIw',
    appId: '1:565159665428:ios:5a8b5e3aa4f3da31e8ac01',
    messagingSenderId: '565159665428',
    projectId: 'laundry-c3745',
    storageBucket: 'laundry-c3745.appspot.com',
    iosBundleId: 'com.example.uas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD82fm2AYQ7dD9MY5SJHIsJtxPPH9ftO60',
    appId: '1:565159665428:web:5404122ab5e024e7e8ac01',
    messagingSenderId: '565159665428',
    projectId: 'laundry-c3745',
    authDomain: 'laundry-c3745.firebaseapp.com',
    storageBucket: 'laundry-c3745.appspot.com',
    measurementId: 'G-S3DQ75CQ34',
  );
}
